version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
  azure-cli: circleci/azure-cli@1.0.0
  path-filtering: circleci/path-filtering@0.1.3

setup: true

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue-config.yml
          mapping: |
            src/test/regress/sql/.* check-flakyness true
            src/test/regress/spec/.* check-flakyness true
